### ISSUE TITLE
Typo in the "Home Assistant in V2" wiki - commands sent to the incorrect command_topic

### ISSUE THREAD

**Issue by qntris** [maragelis/ParadoxRs232toMqtt#71]
Hi Maragelis,

Thank you very much for sharing this project.

What I noticed, is that the Home Assistant V2 wiki has a typo and if not corrected, the commands are not sent to the proper topic:

```
alarm_control_panel:
 platform: mqtt
 state_topic: "paradoxdCTL/hassio/Arm"
 **command_topic:"paradoxCTL/in"**
```

The correct name of the command_topic is "paradox**d**CTL/in"
